# Generated by Django 3.2.18 on 2023-05-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_country', models.CharField(max_length=20)),
                ('youtube_url', models.URLField(max_length=300)),
                ('location_photo_url', models.URLField(max_length=300)),
                ('location_description', models.TextField()),
            ],
        ),
    ]
