# Generated by Django 3.2.18 on 2023-05-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='movielocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
